### ISSUE TITLE
Google vertex error deep in superlinked runstack

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [superlinked/superlinked#66]
**Describe the bug**:

this error is breaking the quick start notebook for superlinked:

`"message": "cannot import name 'ToolConfig' from 'vertexai.preview.generative_models' (/Users/dhruvanand/.local/lib/python3.10/site-packages/vertexai/preview/generative_models.py)",`

https://gist.github.com/dhruv-anand-aintech/ff3d523d48968c9f0b711422cdd8bf05

Run this line by line:
https://github.com/superlinked/superlinked/blob/main/notebook/semantic_search_netflix_titles.ipynb

**Expected behavior**

**System (fill in)**
 - Version: latest

**Additional context**

**Comment by dhruv-anand-aintech** [comment]
ok it got resolved after running pip install vertexai

**Comment by kembala** [comment]
Can you confirm that the issue is that the notebook does not run locally as it needs vertexai, which comes pre-installed on colab, but not locally?

I checked the package by:
```python
import importlib.util

# For illustrative purposes.
package_name = 'vertexai'

spec = importlib.util.find_spec(package_name)
if spec is None:
    print(package_name +" is not installed")
```

The preferred development flow is using the Colab links for now, later on we will invest into testing the framework in different environment setups as well.

Let me know, if I have missed anything.

**Comment by dhruv-anand-aintech** [comment]
I did have it installed locally, but perhaps an old version had an error, or outdated dependencies. `pip install vertexai` also seemed to upgrade it.
