### ISSUE TITLE
saving in qdrant

### ISSUE THREAD

**Issue by sushmar07** [superlinked/superlinked#88]
**Describe the bug**
While using huge data we need to save or store the embeddings while trying to store the embedding in qdrant and using it for llm it did not save the embeddings in qdrant itself.

**To Reproduce**
Steps to reproduce the behavior. Ideally with a code example.

**Expected behavior**
I want you to give me code integrated with llm of storing in qdrant db.

**System (fill in)**
 - Version: [e.g. 0.0.1]

**Additional context**

**Comment by svonava** [comment]
@sushmar07 can you share details of what didn't work?

**Comment by sushmar07** [comment]
just in the rag hr example which you gave or similarity search example
which you gave in colab instead of saving it in memory can you implement by
saving it in qdrant and  use it for query. the integration of the
qdrant part is not working .

**Comment by svonava** [comment]
I see - can you share your code and the error you are getting?

**Comment by sushmar07** [comment]
i have attached a sample file. the code is running but it is not storing in
qdrant db. i have tried everything and i dont know in which collection it
is stored.the embeddings is not being stored at all. please can you
change this.

**Comment by svonava** [comment]
@sushmar07 I believe that attaching a file to the email that you use to respond to this thread doesn't actually add that file here on github. Can you upload here directly?

**Comment by sushmar07** [comment]
Since it is not completed I can't attach it on github that's y I attached
it here.please can u give solution for it.

**Comment by svonava** [comment]
Sorry but I can not see the file when you just attach it to your email response - instead, you have to:
1. Navigate to: https://github.com/superlinked/superlinked/issues/88#issuecomment-2522031259
2. Comment on the thread and upload the file in your web browser.

**Comment by sushmar07** [comment]
[superlinked_new (1).zip](https://github.com/user-attachments/files/18146219/superlinked_new.1.zip)
i have uploaded the file here please resolve the issue of saving the embeddings into qdrant and then using that embeddings in my llm.

**Comment by sushmar07** [comment]
i have attached the file like you have mentioned please can you resolve the
issue.

**Comment by teddego** [comment]
Hey @sushmar07! Thank you for sending us the code. You run this as is? Meaning, this is the exact code you're trying to use in a notebook? Because I see 2 problems:
1. `QdrantVectorDatabase` needs a valid host and api key. I'm quite sure you're using proper args and only added placeholders for us, but if that's not the case and you accidentally left them as they were after copying it from the example, make sure you replace them.
2. The code you sent is intended to be used as a REST application. If you'd like to run an experiment in a notebook, you need to use an interactive application. An example can be found [here](https://colab.research.google.com/github/superlinked/superlinked/blob/main/notebook/rag_hr_knowledgebase.ipynb). For setting up a local REST application you can find instructions [here](https://docs.superlinked.com/run-in-production/index#how-to-start-the-application).

**Comment by sushmar07** [comment]
1. I have used my host and api key
2. can you validate my second problem more clearly if i use rest
application will i be able to save it in qdrant.

**Comment by teddego** [comment]
Sure, you're gonna be able to store the results in Qdrant if you either:
- configure your application to use `sl.InMemorySource` and `sl.InMemoryExecutor` or
- use our [superlinked-server](https://pypi.org/project/superlinked-server/) package and run a REST application

**Comment by sushmar07** [comment]
but while storing inMemory it is temporary right? i want to store  the
embeddings permanently
thats why i had used rest

**Comment by teddego** [comment]
`InMemoryExecutor` doesn't mean the underlying vector database will only store data in-memory, it indicates how it can be interacted with and where is it run. If a a proper `QdrantVectorDatabase` is configured, `InMemoryExecutor` will store the results in it.

**Comment by sushmar07** [comment]
Ok thank you
